// vim: set expandtab:

`include "adder.v"
`include "alu.v"
`include "arm.v"
`include "condcheck.v"
`include "condlogic.v"
`include "controller.v"
`include "datapath.v"
`include "decode.v"
`include "dmem.v"
`include "extend.v"
`include "flopenr.v"
`include "flopr.v"
`include "imem.v"
`include "mux2.v"
`include "mux4.v"
`include "regfile.v"
`include "testbench.v"
`include "top.v"
